services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pymedapp
    command: uvicorn main:app --host 0.0.0.0 --port 8081 --reload
    volumes:
      - .:/app
      - /app/__pycache__
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - RUNNING_ENV=docker
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=exampledb
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=exampledb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U user -d exampledb"]
#      interval: 5s
#      timeout: 5s
#      retries: 5
#      start_period: 5s
    restart: unless-stopped
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#      - PGADMIN_DEFAULT_PASSWORD=12345
#    ports:
#      - "16543:80"
#    depends_on:
#      - db
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin
#    restart: unless-stopped

volumes:
  postgres_data:
#  pgadmin_data:
